#!/usr/bin/env node
/**
 * Copy the app's knob manifest (frontend: tools/knobs/app-knobs.json) into
 * src/experience/appKnobsData.ts, so every knob the app reads is sent by
 * the server explicitly and shows up in the control console.
 *
 *   node scripts/sync-knobs.mjs ../../TAILZU-FRONTEND/tools/knobs/app-knobs.json
 */
import fs from "node:fs";
const src = process.argv[2];
if (!src) { console.error("usage: sync-knobs.mjs <app-knobs.json>"); process.exit(2); }
const m = JSON.parse(fs.readFileSync(src, "utf8"));
const body = `// Generated by scripts/sync-knobs.mjs from the app's tools/knobs/app-knobs.json.
// Edit the app (knob fallbacks) and re-sync; values here are what clients get
// unless catalog.ts or a control rule says otherwise.
export const APP_KNOB_LABELS: Record<string, string> = ${JSON.stringify(m.labels ?? {}, null, 2)};

export const APP_KNOB_FLAGS: Record<string, unknown> = ${JSON.stringify(m.flags ?? {}, null, 2)};

/** Knobs whose app-side default comes from other inputs; sent only if set. */
export const APP_KNOB_DYNAMIC: readonly string[] = ${JSON.stringify(Object.keys(m.dynamic ?? {}), null, 2)};
`;
fs.writeFileSync(new URL("../src/experience/appKnobsData.ts", import.meta.url), body);
console.log(`synced ${Object.keys(m.labels ?? {}).length} labels, ${Object.keys(m.flags ?? {}).length} flags`);
