#!/usr/bin/env node
/**
 * Copy the app's knob manifest (frontend: tools/knobs/app-knobs.json) into
 * src/experience/appKnobsData.ts, so every knob the app reads is sent by
 * the server explicitly and shows up in the control console.
 *
 *   node scripts/sync-knobs.mjs ../../TAILZU-FRONTEND/tools/knobs/app-knobs.json
 */
import fs from "node:fs";
const src = process.argv[2];
const kbSrc = process.argv[3];
if (!src) { console.error("usage: sync-knobs.mjs <app-knobs.json> [keyboard-knobs.json]"); process.exit(2); }
const m = JSON.parse(fs.readFileSync(src, "utf8"));
const body = `// Generated by scripts/sync-knobs.mjs from the app's tools/knobs/app-knobs.json.
// Edit the app (knob fallbacks) and re-sync; values here are what clients get
// unless catalog.ts or a control rule says otherwise.
export const APP_KNOB_LABELS: Record<string, string> = ${JSON.stringify(m.labels ?? {}, null, 2)};

export const APP_KNOB_FLAGS: Record<string, unknown> = ${JSON.stringify(m.flags ?? {}, null, 2)};

/** Knobs whose app-side default comes from other inputs; sent only if set. */
export const APP_KNOB_DYNAMIC: readonly string[] = ${JSON.stringify(Object.keys(m.dynamic ?? {}), null, 2)};
`;
fs.writeFileSync(new URL("../src/experience/appKnobsData.ts", import.meta.url), body);
console.log(`synced ${Object.keys(m.labels ?? {}).length} labels, ${Object.keys(m.flags ?? {}).length} flags`);

if (kbSrc) {
  const k = JSON.parse(fs.readFileSync(kbSrc, "utf8"));
  const pick = (p) => ({ flags: k[p]?.flags ?? {}, labels: k[p]?.labels ?? {}, dynamic: k[p]?.dynamic ?? [] });
  const kb = `// Generated by scripts/sync-knobs.mjs from the app's tools/knobs/keyboard-knobs.json:
// every flag and label each keyboard reads, with its native default. The
// catalog's values win; these fill the rest so every key goes out.
export const KEYBOARD_KNOBS: {
  ios: { flags: Record<string, unknown>; labels: Record<string, string>; dynamic: readonly string[] };
  android: { flags: Record<string, unknown>; labels: Record<string, string>; dynamic: readonly string[] };
} = ${JSON.stringify({ ios: pick("ios"), android: pick("android") }, null, 2)};
`;
  fs.writeFileSync(new URL("../src/experience/keyboardKnobsData.ts", import.meta.url), kb);
  console.log(`synced keyboard knobs: ios ${Object.keys(k.ios.flags).length} flags / ${Object.keys(k.ios.labels).length} labels, android ${Object.keys(k.android.flags).length} flags / ${Object.keys(k.android.labels).length} labels`);
}
