// Generated by scripts/sync-knobs.mjs from the app's tools/knobs/app-knobs.json.
// Edit the app (knob fallbacks) and re-sync; values here are what clients get
// unless catalog.ts or a control rule says otherwise.
export const APP_KNOB_LABELS: Record<string, string> = {
  "offline.body": "Tailzu can't reach its server right now. Check your connection. It will keep trying.",
  "offline.checking": "Checking…",
  "offline.retry": "Try again",
  "offline.retryIn": "Trying again in {s}s",
  "offline.title": "You're offline"
};

export const APP_KNOB_FLAGS: Record<string, unknown> = {
  "app.offline.bodySize": 15,
  "app.offline.buttonRadius": 22,
  "app.offline.buttonText": "#000000",
  "app.offline.devHoldMs": 3000,
  "app.offline.padding": 32,
  "app.offline.retryFactor": 1.6,
  "app.offline.retryMaxMs": 30000,
  "app.offline.retryMs": 8000,
  "app.offline.titleSize": 22
};

/** Knobs whose app-side default comes from other inputs; sent only if set. */
export const APP_KNOB_DYNAMIC: readonly string[] = [
  "app.boot.watchdogMs",
  "app.offline.accent",
  "app.offline.bg",
  "app.offline.devConnection",
  "app.offline.muted",
  "app.offline.text"
];
